using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MySql.Data.MySqlClient;

namespace DatabaseProject.Controllers;

public class ArtistController(ILogger<ArtistController> logger, IConfiguration configuration) : Controller
{
    // GET
    public IActionResult Index()
    {
        ViewBag.ArtistNames = GetArtists();
        CreateArtistsTable();
        return View();
    }
     private void CreateArtistsTable()
     {
         string result = "";
         // Okay using raw SQL here bc no user input is needed - no security issue here
         string commandString = "SELECT artist_name FROM Artist";
         try
         {
             using var connection = new MySqlConnection(configuration.GetConnectionString("mySqlConn"));
             connection.Open();
             using var command = connection.CreateCommand();
             command.CommandText = commandString;
             using var reader = command.ExecuteReader();
             while (reader.Read())
             {
                 result += $"""
                            <tr>
                              <td>{reader[0]}</td>
                            </tr>
                            """;
             }
         }
         catch (MySqlException ex)
         {
             logger.LogError($"Error {ex.Number} has occurred: {ex.Message}");
         }
 
         ViewBag.Table = result;
     }

    // Should be the same or similar for new album and new song
    public IActionResult AddNewArtist(string artistName)
    {
        try
        {
            using var connection = new MySqlConnection(configuration.GetConnectionString("mySqlConn"));
            connection.Open();
            using var command = connection.CreateCommand();
            // Don't add id because it is autogenerated
            command.CommandText = "INSERT INTO Artist (artist_name) VALUES (@artistName)";
            command.Parameters.AddWithValue("@artistName", artistName);
            command.Prepare();
            command.ExecuteNonQuery();
        }
        catch (MySqlException ex)
        {
            if (ex.Number == 1065)
            {
                logger.LogError($"Entry {artistName} already exists");
                return RedirectToAction("Index");
            }
            logger.LogError($"Error {ex.Number} has occurred: {ex.Message}");
            throw;
        }

        return RedirectToAction("Index");
    }

    public IActionResult DeleteArtist(uint id)
    {
        try
        {
            using var connection = new MySqlConnection(configuration.GetConnectionString("mySqlConn"));
            connection.Open();
            using var command = connection.CreateCommand();
            command.CommandText = "DELETE FROM Artist WHERE id = @id";
            command.Parameters.AddWithValue("@id", id);
            command.Prepare();
            int rowAffected = command.ExecuteNonQuery();
            logger.LogInformation($"Command String: {command.CommandText} ID: {id}");
            logger.LogInformation($"Number of rows affected {rowAffected}");
        }
        catch (MySqlException ex)
        {
            logger.LogError($"Error {ex.Number} has occurred: {ex.Message}");
            throw;
        }

        return RedirectToAction("Index");
    }

    public IActionResult UpdateArtist(uint id, string artistName)
    {
        try
        {
            using var connection = new MySqlConnection(configuration.GetConnectionString("mySqlConn"));
            connection.Open();
            using var command = connection.CreateCommand();
            command.CommandText = "UPDATE Artist SET artist_name = @artistName WHERE id = @id";
            command.Parameters.AddWithValue("@artistName", artistName);
            command.Parameters.AddWithValue("@id", id);
            command.Prepare();
            command.ExecuteNonQuery();
        }
        catch (MySqlException ex)
        {
            if (ex.Number == 1065)
            {
                logger.LogError($"Entry {artistName} already exists");
                return RedirectToAction("Index");
            }
            logger.LogError($"Error {ex.Number} has occurred: {ex.Message}");
            throw;
        }

        return RedirectToAction("Index");
    }

    private List<SelectListItem> GetArtists()
    {
        List<SelectListItem> artists = new List<SelectListItem>();
        try
        {
            using var connection = new MySqlConnection(configuration.GetConnectionString("mySqlConn"));
            connection.Open();
            using var command = connection.CreateCommand();
            // id, artist_name
            command.CommandText = "SELECT * FROM Artist";
            
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                artists.Add(new SelectListItem(reader[1].ToString(), reader[0].ToString()));
            }
        }
        catch (MySqlException ex)
        {
            logger.LogError($"Error {ex.Number} has occurred: {ex.Message}");
            throw;
        }
        return artists;
    }
}